### ISSUE TITLE
Initial ARM Support

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/lsc-sde#33]
At present all container images are only being built to amd64 architecture, these will need to support arm64 architectures as well

**Comment by vvcb** [comment]
Is this just for JupyterHub or more widely?

What impact does this have?

I know there will be specifics when building Jupyter single-user images for GPU workloads (in fact there is one that I already built that needs updating). 

But it will be good to understand how CPU architecture impacts what we are trying to accomplish and where this sits within the wider priorities.

**Comment by qcaas-nhs-sjt** [comment]
@vvcb This is to enable Mike to be able to run a local environment, as his machine is a mac. I've managed to convert around half of the services already as the package management can largely take care of it in many cases it's just been getting it to do include the amd64 platform which is a quick change. 
* One of our services the **AKS DNS Operator** isn't building but isn't essential as it isn't used in a local environment, so i've bypassed this and will come back round to it.
* The jupyter notebooks refer to amd64 directly with some of the packages we're installing so i've made some changes and hopefully they will be able to work so fingers crossed. 
* OHDSI i'm not so sure about yet, in theory it should be fine but will have a look once I've got jupyter running in full.

**Comment by vvcb** [comment]
It will be good to rationalise other use cases this effort will benefit. Else it may be simpler to get Mike a PC!

For instance, Datashield on Pi once I find the funding for that.

**Comment by qcaas-nhs-sjt** [comment]
Linking to lsc-sde/lsc-sde#46

**Comment by qcaas-nhs-sjt** [comment]
@vvcb @m1p1h  I'm wondering if this is something we want to invest any more time in at the moment? We've done a decent amount on this. The issues that we are having right now seem to be unique to macos which per the comments above may not be something we need to address right now, instead I'm wondering if it may be better to get Mike access to something using the amd64 architecture, whether that be a VM or a desktop/laptop? Am happy either way personally

**Comment by vvcb** [comment]
We should be able to separate out the cluster administrator and application developer personas to allow development on the same cluster or clusters. 

Why should every developer have access to their own cluster?

The local development option is a nice one to have but does not scale if we are supporting multiple CPU/GPU architectures across multiple microservices.

**Comment by qcaas-nhs-sjt** [comment]
> We should be able to separate out the cluster administrator and application developer personas to allow development on the same cluster or clusters.
> 
> Why should every developer have access to their own cluster?
> 
> The local development option is a nice one to have but does not scale if we are supporting multiple CPU/GPU architectures across multiple microservices.

In my case I do this because I do not have direct access to the sandbox cluster, not sure whether Mike will either. The solution will also need some adaptation to allow multiple instances on the same cluster, and there are of course some questions surrounding shared components and how to handle multiple databases, etc. This is totally doable but will require a little work, I'll create a ticket for this as I think it's something we may want to support anyway.

As for development access, the option of a developer VM for each of us might be the best option, or we revisit the option of providing VPN access for developers, which would be my personal preference. I'm happy with either option personally (so long as the VM is powerful enough) but if we change the routes in I think we'll need to get approval for this

**Comment by qcaas-nhs-sjt** [comment]
Further to this have created ticket #52 for multiple instances on the same cluster

**Comment by vvcb** [comment]
I will pick up the k8s specific convo on #52. 

1. Regarding access to the cluster - I am at a slight/significant advantage as I am on the internal network anyway and my work laptop is already setup as a dev box. 
2. For external developer access, I have previously suggested -> https://azure.microsoft.com/en-gb/pricing/details/dev-box/
3. However, for the data platform work, our infrastructure team have used the on-prem VDI environment to provide access. I think that may be too limiting for our use case. 
4. Another alternative would be to provide external researchers our hardware - likely to be false economy - capital expense, depreciation, time to configure, etc. 
5. VPN access to developer's own machine is unlikely to get approved (although I know @qcaas-nhs-sjt loves the beast of a machine he has) - but it will be good to understand why it won't get approved - we may end up seeing that network topology we asked for sometime ago.

**Comment by qcaas-nhs-sjt** [comment]
>     1. Regarding access to the cluster - I am at a slight/significant advantage as I am on the internal network anyway and my work laptop is already setup as a dev box.

I think that this could actually be a drawback rather than a benefit, having multiple routes into the system for the various developers gives us numerous different problems to address and issues to support not to mention the overhead of managing these from a security point of view. I would say having one route for developers to manage the solution also makes sure that we're all aligned on our way of working, which will make us work much more effectively as a team and to introduce new developers into the fray. 

>     2. For external developer access, I have previously suggested -> https://azure.microsoft.com/en-gb/pricing/details/dev-box/

I'm absolutely fine with this as a solution, this has the added benefit of being something easily replicable for new users but I think we will need to request this either of Paul's team or of Pheonix to get this implemented.

>     3. However, for the data platform work, our infrastructure team have used the on-prem VDI environment to provide access. I think that may be too limiting for our use case.

My concern about staging anything inside of the on-prem is that then means that we will be passing through a lot of networks that are totally irrelevant to us and will have network access to a load of things we won't need. It also becomes more difficult to manage as then it's not just the azure firewalls and NSG's we have to worry about but it's all of the on-premise routes and firewalls as well

>     4. Another alternative would be to provide external researchers our hardware - likely to be false economy - capital expense, depreciation, time to configure, etc.

Agreed, this is likely a false economy and there are other overheads and again more issues to do with networking which adds complexity.
 
>     5. VPN access to developer's own machine is unlikely to get approved (although I know @qcaas-nhs-sjt loves the beast of a machine he has) - but it will be good to understand why it won't get approved - we may end up seeing that network topology we asked for sometime ago.

I agree, this is unlikely, in past discussions i think that was largely because they were worried about what other NHS systems we would have access to. I mentioned that they could manage this through limiting routing. So instead of going in to the LTH VPN as you do:

```mermaid
flowchart LR
    User --> |VPN| LTH[LTH Network] --> AzureHubVNET[Azure Hub VNET]

    subgraph AzureHub [Azure Hub Network]
        AzureHubVNET
    end

    subgraph LSCSDE [LSC SDE Network]
       direction TB
       AzureSpokeDev[Dev VNET] 
       ~~~
       AzureSpokeSandbox[Sandbox VNET] 
       ~~~
       AzureSpokeProd[Prod VNET]
    end

    LSCSDEDEV[LSC SDE Developer] -->|VPN| LTH
    AzureHub --> LSCSDE

```
It would go through a specific VPN which wouldn't route through the hub network:

```mermaid
flowchart LR
    User --> |VPN| LTH[LTH Network] --> AzureHubVNET[Azure Hub VNET]

    subgraph AzureHub [Azure Hub Network]
        AzureHubVNET
    end

    subgraph LSCSDE [LSC SDE Network]
       direction TB
       AzureSpokeDev[Dev VNET] 
       ~~~
       AzureSpokeSandbox[Sandbox VNET] 
       ~~~
       AzureSpokeProd[Prod VNET]
    end

    LSCSDEDEV[LSC SDE Developer] -->|VPN| DevNetwork[Developer VNET] 

    subgraph Dev [LSC SDE Developer Network]
        DevNetwork
    end

    AzureHub --> LSCSDE
    DevNetwork --> LSCSDE 
```
The Developer Network wouldn't route through the hub network, so the hub wouldn't see the developers or vice versa. Of course, in theory you could jump onto a machine on the  LSC SDE Network and see everything that that machine can see, but that will be the case regardless of the solution.

In any case I think that the most likely route to get approved is the devbox side of things, so probably the easiest thing to request and then we can use the same hardware which will eliminate the need for arm support for the time being at least.

**Comment by qcaas-nhs-sjt** [comment]
Am closing this issue for now as we are provisioning dev boxes to work around this, may pickup again in the future on a new ticket though
