### ISSUE TITLE
Allow multiple instances on same cluster

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/lsc-sde#52]
As architect I would like to be able to host multiple instances of the software on the same cluster. 

Questions:
* How do we handle shared components?
* How do we handle multiple databases?

**Comment by qcaas-nhs-sjt** [comment]
Linked #46

**Comment by vvcb** [comment]
__TL;DR__ - Can we start with the simplest option of using namespaces and build additional complexity where we need to?

## JupyterHub

For many 'self-contained' applications, JupyterHub being one of them, k8s namespaces should provide sufficient isolation for multiple instances to run on the same cluster. However, private DNS zone registration will be an obvious trip up without some configuration - including the namespace in the DNS entry should solve this e.g. `vc-jupyter-sandbox.xlscsde.nhs.uk`,  `sjt-jupyter-sandbox.xlscsde.nhs.uk`, etc. 

JupyterHub uses its own sqlite database (we really must switch to Postgres at some point) and each instance will be fully self-contained. See https://discourse.jupyter.org/t/multiple-hubs-per-kubernetes-cluster/2750 and https://discourse.jupyter.org/t/spawn-multiple-hubs-in-the-same-kubernetes-cluster-using-helm/4584. 

## OHDSI
Shared components will be trickier but not necessarily from a k8s perspective. For instance, OHDSI stack expects Postgres as part of the stack and not as a shared component between multiple instances of WebAPI/Atlas. So, this is not a k8s issue but us trying to re-engineer a complex, open-source application that has been built over a decade - we don't have the resources to do this. 

If we are setting up multiple OHDSI stacks for development, each one should come with its own postgres instance - and this could be a statefulset in dev (if cost becomes an issue) and managed Postgres in test/prod. 

## DataSHIELD

DataSHIELD is probably similar to OHDSI and we should try and keep things entirely self-contained on k8s in dev and use managed services in test/prod is such a switch is even possible. 

## Other microservices

For now, anything I built in LTH will happily play with namespace isolation and shouldn't be a problem. 

@m1p1h , @qcaas-nhs-sjt  - please post links to any reading material on best practices, etc. and we can discuss further.

**Comment by qcaas-nhs-sjt** [comment]
My take:

# LSC SDE Components

## Analytics Workspace Management & Jupyter Hub Integration
This implements CRD's which are at the cluster level, as a result we also implement roles which are likewise at the cluster level. While the custom resources they define are scoped at the namespace level, the CRD's themselves are not. As this was not a previous use case, the names are currently hard coded. To allow us to run multiple versions of the CRD's in an environment without impacting other services we would need to make them useable.

To facilitate multiple versions on the same environment we will have to make them configurable in the following packages:
* Workspace Management - Python Module
* Workspace Management - Helm Chart
* Workspace Management - Flux Configuration
* Custom Jupyter Hub Docker Image
* Workspace Management Portal - Low priority as not currently live

## AKS DNS Operator
We don't need to have multiple versions of this as it will work across the board, we just need to make sure that the annotation's on the ingress resources is unique for each resource so that it doesn't get confused. This will impact anything that exposes an ingress:
* Juptyer Hub
* OHDSI

## Secrets Distributor
This is a very simple tool so I don't think we need more than one of these on a cluster at the moment. That said if in the future we did, we would need to build in a responsibility chain to say which of the instances of the secrets distributor is responsible for which secrets. This would require changes to:
* Secrets Distributor Docker Image
* Secrets Distributor Helm Chart
* Secrets Distributor Flux Configuration

# Non LSE-SDE Product Components
## Jupyter Hub
This implements cluster level objects, hopefully the names of these are configurable but this will need investigation and possible changes to the flux configuration

## OHDSI
At present the helm charts for OHDSI does not implement any cluster level objects so this should be relatively easy to isolate

# Wraparound Components
## Keda
A single instance of keda on a cluster for all environments should be fine

## Cert Manager / Trust Manager
A single instance of cert manager on a cluster for all environments should be fine

## Nginx
I see no reason at present to have multiple instances of nginx on a cluster with our current setup, though this might change in future.

**Comment by qcaas-nhs-sjt** [comment]
Have got this working with OHDSI so far, but it's sharing the database of the actual OHDSI environment, still need to get it working with another database name but will double this up with lsc-sde/iac-helm-ohdsi#5

Will look at getting second instance of jupyterhub running first

**Comment by qcaas-nhs-sjt** [comment]
Got jupyter up and running but with a couple of caveats:
- App Registrations will require manual config - these changes will be overwritten with any changes to terraform, this needs to be amended so that terraform ignores changes. 
- The process for updating the app registration also needs documenting
- Workspaces are hard-coded to use jupyter-default as the storage class for new persistent volume claims, this needs to be made configurable
