### ISSUE TITLE
Remove unused/redundant single user image repositories

### ISSUE THREAD

**Issue by vvcb** [lsc-sde/lsc-sde#53]
The following github repos can be removed. Let us revisit how we build and maintain a standard stack of images similar to https://jupyter-docker-stacks.readthedocs.io/en/latest/using/selecting.html#image-relationships and https://github.com/jupyter/docker-stacks

- [x] [docker-beamtree-rstudio](https://github.com/lsc-sde/docker-beamtree-rstudio)
- [x] [docker-cpu-dfu](https://github.com/lsc-sde/docker-cpu-dfu)
- [x] [docker-datascience-code-server](https://github.com/lsc-sde/docker-datascience-code-server)
- [x] [docker-datascience-nlp](https://github.com/lsc-sde/docker-datascience-nlp)
- [x] [docker-datascience-odbc](https://github.com/lsc-sde/docker-datascience-odbc)
- [x] [docker-dfu-jupyterlab](https://github.com/lsc-sde/docker-dfu-jupyterlab)
- [x] [docker-fft-notebook](https://github.com/lsc-sde/docker-fft-notebook)
- [x] [docker-lancuni-grp-prj-2021-notebook](https://github.com/lsc-sde/docker-lancuni-grp-prj-2021-notebook)
- [x] [docker-octave-notebook](https://github.com/lsc-sde/docker-octave-notebook)
- [x] [docker-rstudio-notebook](https://github.com/lsc-sde/docker-rstudio-notebook)

Linked to https://github.com/lsc-sde/lsc-sde/issues/46

**Comment by qcaas-nhs-sjt** [comment]
added deprecation notices to all repositories, removed from submodules in core repository and have archived the repositories.

Please note that these have not been removed, just archived as is best practice.
