### ISSUE TITLE
Java Libraries for CRD's

### ISSUE THREAD

**Issue by qcaas-nhs-sjt** [lsc-sde/lsc-sde#63]
As architect, I would like to be able to convert the CRD's from their current yaml to Java classes automatically to reflect changes made to the CRD's

---
### AC
- Convert CRD to java classes
- Pipeline that executes on changes to the CRD's that updates the java libraries as appropriate
- Generate Javadocs for the libraries

**Comment by vvcb** [comment]
@qcaas-nhs-sjt , let's discuss this in more detail this week in the context of available options, complexity and maintainability. I am particularly interested in how ELabs have implemented this.

**Comment by qcaas-nhs-sjt** [comment]
@vvcb sorry I think there is some confusion here, this is just an enabler, to allow ourselves and others using java to interact with the workspace management system. The actual guacamole implementation will happen as part of issue #49 which is currently on hold

**Comment by qcaas-nhs-sjt** [comment]
This has been built and initial version is deployed and is documented here:

https://lsc-sde.github.io/lsc-sde/Secure-Data-Environment/Developers/Interoperability/Java/Deploying.html

with Javadocs for this module here:

https://lsc-sde.github.io/java-analytics-workspace-management-models/
